services:
  - type: web
    name: service-users
    env: python
    rootDir: backend/service-users
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: web
    name: service-gateway
    env: python
    rootDir: backend/service-gateway
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: web
    name: service-farms
    env: python
    rootDir: backend/service-farms
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: web
    name: service-marketplace
    env: python
    rootDir: backend/service-marketplace
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: web
    name: service-community
    env: python
    rootDir: backend/service-community
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: web
    name: service-chat
    env: python
    rootDir: backend/service-chat
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
